#!/usr/bin/env python3
"""Generate each app's design tokens from `tokens.json`.

Four apps in four languages cannot share an import, so they share a generator
instead. Run this after editing `tokens.json`; CI re-runs it and fails if the
committed output no longer matches, which is what stops the four palettes from
drifting apart the way they had.

    python3 assets/design/generate.py          # write the files
    python3 assets/design/generate.py --check  # fail if anything is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = Path(__file__).resolve().parent / "tokens.json"

BANNER = "Generated by assets/design/generate.py from assets/design/tokens.json."
DO_NOT_EDIT = "Do not edit by hand — edit the tokens and regenerate."


def load() -> dict:
    return json.loads(TOKENS.read_text())


def strip_comments(group: dict) -> dict:
    return {k: v for k, v in group.items() if not k.startswith("$")}


def rgb(hex_colour: str) -> tuple[int, int, int]:
    value = hex_colour.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def mix(hex_colour: str, other: str, amount: float) -> str:
    """Blend `amount` of `other` into `hex_colour`."""
    a, b = rgb(hex_colour), rgb(other)
    blended = tuple(round(x + (y - x) * amount) for x, y in zip(a, b))
    return "#{:02x}{:02x}{:02x}".format(*blended)


def rust_ident(name: str) -> str:
    return name.replace("-", "_").upper()


# ---------------------------------------------------------------- Rust output

def rust_tokens(tokens: dict, accent_name: str, module_doc: str) -> str:
    accent = tokens["accents"][accent_name]
    lines = [
        f"//! {module_doc}",
        "//!",
        f"//! {BANNER}",
        f"//! {DO_NOT_EDIT}",
        "",
        "#![allow(dead_code)]",
        "",
        "/// A token colour, as 8-bit sRGB.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Rgb(pub u8, pub u8, pub u8);",
        "",
        "impl Rgb {",
        "    /// The three channels as 0.0–1.0 sRGB, for GPU and iced call sites.",
        "    pub const fn f32(self) -> [f32; 3] {",
        "        [",
        "            self.0 as f32 / 255.0,",
        "            self.1 as f32 / 255.0,",
        "            self.2 as f32 / 255.0,",
        "        ]",
        "    }",
        "",
        "    /// The three channels plus an alpha, for GPU vertex data.",
        "    pub const fn rgba(self, alpha: f32) -> [f32; 4] {",
        "        let [r, g, b] = self.f32();",
        "        [r, g, b, alpha]",
        "    }",
        "}",
        "",
    ]

    def emit(group: str, doc: str) -> None:
        lines.append(f"// {doc}")
        for name, value in strip_comments(tokens[group]).items():
            r, g, b = rgb(value)
            lines.append(f"/// `{value}`")
            lines.append(f"pub const {rust_ident(name)}: Rgb = Rgb({r}, {g}, {b});")
        lines.append("")

    emit("ground", "The shared dark ground.")
    emit("text", "Text, in three weights.")
    emit("semantic", "Meaning-bearing colours, identical in every app.")

    chart = strip_comments(tokens["chart"])
    lines.append("/// Categorical colours for data, in order. Cycle with `CHART[i % CHART.len()]`.")
    lines.append(f"pub const CHART: [Rgb; {len(chart)}] = [")
    # rustfmt aligns trailing comments in an array to a common column, so the
    # generator has to as well — otherwise every regeneration leaves the file
    # failing `rustfmt --check`.
    entries = [(f"    Rgb({r}, {g}, {b}),", value) for value in chart.values() for r, g, b in [rgb(value)]]
    width = max(len(code) for code, _ in entries)
    for code, value in entries:
        lines.append(f"{code.ljust(width)} // {value}")
    lines.append("];")
    lines.append("")

    r, g, b = rgb(accent)
    lines += [
        f"// This app's accent, from its icon in assets/icons/{accent_name}.svg.",
        f"/// `{accent}`",
        f"pub const ACCENT: Rgb = Rgb({r}, {g}, {b});",
    ]
    hover = mix(accent, "#000000", 0.18)
    r, g, b = rgb(hover)
    lines += [
        f"/// `{hover}` — the accent at 82%, for a pressed or hovered surface.",
        f"pub const ACCENT_HOVER: Rgb = Rgb({r}, {g}, {b});",
        "",
        "// Every other app's accent, so one app can point at another and be believed.",
    ]
    for name, value in strip_comments(tokens["accents"]).items():
        r, g, b = rgb(value)
        lines.append(f"/// `{value}` — {name}")
        lines.append(f"pub const ACCENT_{name.upper()}: Rgb = Rgb({r}, {g}, {b});")
    lines.append("")

    lines.append("// Motion, in milliseconds.")
    for name, value in strip_comments(tokens["motion"]).items():
        if name.endswith("-ms"):
            lines.append(f"pub const {rust_ident(name)}: u64 = {value};")
    lines.append("")

    # One trailing newline, not a trailing blank line.
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------- CSS output

def css_tokens(tokens: dict, accent_name: str, purpose: str) -> str:
    accent = tokens["accents"][accent_name]
    lines = [
        "/*",
        f" * {purpose}",
        " *",
        f" * {BANNER}",
        f" * {DO_NOT_EDIT}",
        " */",
        "",
        ":root {",
        "  color-scheme: dark;",
        "",
        "  /* The shared dark ground. */",
    ]
    for name, value in strip_comments(tokens["ground"]).items():
        css_name = "bg" if name == "ground" else name
        lines.append(f"  --{css_name}: {value};")

    lines += ["", "  /* Text, in three weights. */"]
    for name, value in strip_comments(tokens["text"]).items():
        lines.append(f"  --{name}: {value};")

    lines += ["", "  /* Meaning-bearing colours, identical in every app. */"]
    for name, value in strip_comments(tokens["semantic"]).items():
        lines.append(f"  --{name}: {value};")
        lines.append(f"  --{name}-hover: {mix(value, '#000000', 0.18)};")

    lines += ["", "  /* Categorical colours for data. */"]
    for name, value in strip_comments(tokens["chart"]).items():
        lines.append(f"  --{name}: {value};")

    lines += [
        "",
        f"  /* This app's accent, from assets/icons/{accent_name}.svg. */",
        f"  --accent: {accent};",
        f"  --accent-hover: {mix(accent, '#000000', 0.18)};",
        "  --accent-soft: color-mix(in srgb, var(--accent) 18%, transparent);",
        "  --on-accent: %s;" % ("#08080a" if is_light(accent) else "#f4f4f5"),
        "",
        "  /* Every other app's accent. */",
    ]
    for name, value in strip_comments(tokens["accents"]).items():
        lines.append(f"  --accent-{name}: {value};")

    lines += ["", "  /* Spacing. */"]
    for name, value in strip_comments(tokens["space"]).items():
        lines.append(f"  --space-{name}: {value}px;")

    lines += ["", "  /* Corner radii. */"]
    for name, value in strip_comments(tokens["radius"]).items():
        css_name = "radius" if name == "md" else f"radius-{name}"
        lines.append(f"  --{css_name}: {value}px;")

    lines += ["", "  /* Motion. */", f"  --ease: {tokens['motion']['ease']};"]
    for name, value in strip_comments(tokens["motion"]).items():
        if name.endswith("-ms"):
            lines.append(f"  --duration-{name[:-3]}: {value}ms;")

    lines += ["", "  /* Type. */"]
    for name, value in strip_comments(tokens["type"]).items():
        lines.append(f"  --font-{name}: {value};")

    lines += ["", "  /* Elevation. */"]
    for name, value in strip_comments(tokens["elevation"]).items():
        lines.append(f"  --shadow-{name}: {value};")

    lines += ["}", ""]
    return "\n".join(lines)


def is_light(hex_colour: str) -> bool:
    """Whether text on this colour should be dark. Rec. 709 luma."""
    r, g, b = rgb(hex_colour)
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) > 140


# ---------------------------------------------------------------- SVG output

def icon(tokens: dict, app: str, title: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-labelledby="title">\n'
        f"  <title>{title}</title>\n"
        f'  <circle cx="128" cy="128" r="120" fill="{tokens["brand"]["ink"]}"/>\n'
        f'  <circle cx="128" cy="128" r="44" fill="{tokens["accents"][app]}"/>\n'
        "</svg>\n"
    )


# --------------------------------------------------------------------- driver

def outputs(tokens: dict) -> dict[Path, str]:
    return {
        ROOT / "src/app/tokens.rs": rust_tokens(
            tokens, "yalive", "The ecosystem's design tokens, for the terminal interface."
        ),
        ROOT / "yGraphy/src/tokens.rs": rust_tokens(
            tokens, "ygraphy", "The ecosystem's design tokens, for the graph."
        ),
        ROOT / "yClippy/src/tokens.css": css_tokens(
            tokens, "yclippy", "The ecosystem's design tokens, for yClippy."
        ),
        ROOT / "yReviewy/src/tokens.css": css_tokens(
            tokens, "yreviewy", "The ecosystem's design tokens, for yReviewy."
        ),
        ROOT / "assets/icons/yalive.svg": icon(tokens, "yalive", "yalive TUI"),
        ROOT / "assets/icons/ygraphy.svg": icon(tokens, "ygraphy", "yGraphy"),
        ROOT / "assets/icons/yreviewy.svg": icon(tokens, "yreviewy", "yReviewy"),
        ROOT / "assets/icons/yclippy.svg": icon(tokens, "yclippy", "yClippy"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any output is stale")
    args = parser.parse_args()

    tokens = load()
    stale: list[Path] = []
    for path, content in outputs(tokens).items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        print("stale, regenerate with `python3 assets/design/generate.py`:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if args.check:
        print("design tokens are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
