//! The ecosystem's design tokens, for the terminal interface.
//!
//! Generated by assets/design/generate.py from assets/design/tokens.json.
//! Do not edit by hand — edit the tokens and regenerate.

#![allow(dead_code)]

/// A token colour, as 8-bit sRGB.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb(pub u8, pub u8, pub u8);

impl Rgb {
    /// The three channels as 0.0–1.0 sRGB, for GPU and iced call sites.
    pub const fn f32(self) -> [f32; 3] {
        [
            self.0 as f32 / 255.0,
            self.1 as f32 / 255.0,
            self.2 as f32 / 255.0,
        ]
    }

    /// The three channels plus an alpha, for GPU vertex data.
    pub const fn rgba(self, alpha: f32) -> [f32; 4] {
        let [r, g, b] = self.f32();
        [r, g, b, alpha]
    }
}

// The shared dark ground.
/// `#08080a`
pub const GROUND: Rgb = Rgb(8, 8, 10);
/// `#0f0f12`
pub const SURFACE: Rgb = Rgb(15, 15, 18);
/// `#1a1a1f`
pub const SURFACE_HI: Rgb = Rgb(26, 26, 31);
/// `#212128`
pub const SURFACE_ACTIVE: Rgb = Rgb(33, 33, 40);
/// `#1f1f24`
pub const BORDER: Rgb = Rgb(31, 31, 36);
/// `#2a2a30`
pub const BORDER_HI: Rgb = Rgb(42, 42, 48);

// Text, in three weights.
/// `#f4f4f5`
pub const TEXT: Rgb = Rgb(244, 244, 245);
/// `#a1a1aa`
pub const TEXT_DIM: Rgb = Rgb(161, 161, 170);
/// `#52525b`
pub const TEXT_FAINT: Rgb = Rgb(82, 82, 91);

// Meaning-bearing colours, identical in every app.
/// `#22c55e`
pub const SUCCESS: Rgb = Rgb(34, 197, 94);
/// `#f59e0b`
pub const WARNING: Rgb = Rgb(245, 158, 11);
/// `#ef4444`
pub const DANGER: Rgb = Rgb(239, 68, 68);

/// Categorical colours for data, in order. Cycle with `CHART[i % CHART.len()]`.
pub const CHART: [Rgb; 8] = [
    Rgb(102, 173, 235), // #66adeb
    Rgb(92, 204, 158),  // #5ccc9e
    Rgb(235, 158, 92),  // #eb9e5c
    Rgb(199, 133, 235), // #c785eb
    Rgb(240, 117, 133), // #f07585
    Rgb(133, 219, 219), // #85dbdb
    Rgb(219, 204, 107), // #dbcc6b
    Rgb(158, 179, 240), // #9eb3f0
];

// This app's accent, from its icon in assets/icons/yalive.svg.
/// `#168bff`
pub const ACCENT: Rgb = Rgb(22, 139, 255);
/// `#1272d1` — the accent at 82%, for a pressed or hovered surface.
pub const ACCENT_HOVER: Rgb = Rgb(18, 114, 209);

// Every other app's accent, so one app can point at another and be believed.
/// `#168bff` — yalive
pub const ACCENT_YALIVE: Rgb = Rgb(22, 139, 255);
/// `#ff3b30` — ygraphy
pub const ACCENT_YGRAPHY: Rgb = Rgb(255, 59, 48);
/// `#b7ff2a` — yreviewy
pub const ACCENT_YREVIEWY: Rgb = Rgb(183, 255, 42);
/// `#ff9f0a` — yclippy
pub const ACCENT_YCLIPPY: Rgb = Rgb(255, 159, 10);

// Motion, in milliseconds.
pub const FAST_MS: u64 = 120;
pub const BASE_MS: u64 = 200;
pub const SLOW_MS: u64 = 320;
